# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4f1d976fd381bb72fc1bbda0b0f867fb0ae03b9828670cafff998b504c71b26aa454fe61152078a59427cfdb71e22f642919edaafc98242b98b93fa8d8a4b04

test:
  secret_key_base: b1af6c4d9f62b22bbdf9b1f14ac3400cc756b1bb1e3c9360e02dee5fc0a25c1e2d50468e0954008e4c32399efaadcabbc228bcf7f0eae785141af1e9fae20f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
